title: CharlieKirk.report
theme: minima

titles_from_headings:
  enabled: true
  strip_title: true

header_pages:
  - celebration.md
  - engravings.md
  - foreknowledge.md
  - shunning.md
  - views.md
